### ISSUE TITLE
non squared images/videos

### ISSUE THREAD

**Issue by tcapelle** [lucidrains/STAM-pytorch#2]
Nice work!
Would you mind helping me use this on non squared images?

**Comment by tcapelle** [comment]
I think that I found a solution, doing:
```
num_patches = (image_size[0] // patch_size) * (image_size[1] // patch_size)
```

and passing a tuple as `image_size`

**Comment by lucidrains** [comment]
@tcapelle try 0.0.4! you just have to make sure your height and width are less than `image_size` and divisible by `patch_size`
